# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

env:
  PROJECT_VERSION: "1.0.0-${{GITHUB_SHA::7}}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet --version
      - name: Check code format
        run: dotnet format --verify-no-changes
      - name: Run unit tests
        run: dotnet test ./HelloWorld.Tests 
      - name: Create package
        run: dotnet pack /p:Version="${PROJECT_VERSION} --artifacts-path=./pkg"
      - name: Release package
        run: gh release create v"${PROJECT_VERSION}" ./pkg/*.nupkg
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
