# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PKG_VERSION_PREFIX: '1.0.0'

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet --version
      - name: Check code format
        run: dotnet format --verify-no-changes
      - name: Run unit tests
        run: dotnet test ./HelloWorld.Tests 
      - name: Set package release suffix
        run: echo "PKG_VERSION_SUFFIX=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Create package
        run: dotnet pack /p:VersionPrefix="${PKG_VERSION_PREFIX}" --version-suffix="${PKG_VERSION_SUFFIX}" --artifacts-path=./artifacts
      - name: Release package
        run: gh release create v"${PKG_VERSION_PREFIX}-${PKG_VERSION_SUFFIX}" ./artifacts/package/release/*.nupkg
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
